Added project
MarinaGotka/JavaTraining pull request #1
Opened 2021-04-05 18:46 UTC by MarinaGotka

2021-04-06 08:55 UTC, artemmoroz requested changes

2021-04-06 08:55 UTC, artemmoroz commented on .idea/.gitignore
> +/workspace.xml
you need to add all files folders that are related to idea and so on. u can take a look site https://www.toptal.com/developers/gitignore

2021-04-06 08:55 UTC, artemmoroz commented on ConsoleApp/pom.xml
> +    <artifactId>ConsoleApp</artifactId>
java naming conventions, everything besides class names - from lower case, and camel case

2021-04-06 08:55 UTC, artemmoroz commented on Store/src/main/java/Category.java
> +    public ArrayList<Product> ProductList;
there shold be List interface

2021-04-06 08:55 UTC, artemmoroz commented on Store/src/main/java/Category.java
> +        final String[][] table = new String[ProductList.toArray().length + 1][];
seems that it is overengineering, just iterate over list of categories and inside iterate products

2021-04-06 08:55 UTC, artemmoroz commented on Store/src/main/java/Product.java
> +    public String[] GetArrayForPrint(){
in java there are toString method that u can override

2021-04-13 16:25 UTC, MarinaGotka commented on Store/src/main/java/Category.java
> +    public ArrayList<Product> ProductList;
Here, yes, but if I understand correctly, we can only use ArrayList to instantiate this list. 
In C# there is List class so it can be used directly)

2021-04-13 16:31 UTC, merged