04 collections
MarinaGotka/JavaTraining pull request #3
Opened 2021-05-07 07:58 UTC by MarinaGotka

task #04_Collections

Added support of sort, top, quit commands for Store

2021-05-07 09:01 UTC, artemmoroz requested changes

2021-05-18 15:29 UTC, artemmoroz approved these changes

2021-05-18 15:29 UTC, artemmoroz commented on store/src/main/java/by/issoft/store/helpers/StoreHelper.java
> +    public List<Product> sortAllProducts(Map sortBy) {
do not leave just Map, in that case, compiler could not check( and help you) on the compilation phase

2021-05-18 15:29 UTC, artemmoroz commented on store/src/main/java/by/issoft/store/helpers/comparators/ProductComparator.java
> +            String propertyValue = product.getClass().getDeclaredField(property).get(product).toString();
very raw solution, could be better (in future)

2021-05-18 18:50 UTC, MarinaGotka commented on store/src/main/java/by/issoft/store/helpers/StoreHelper.java
> +    public List<Product> sortAllProducts(Map sortBy) {
Done, thanks

2021-05-18 18:51 UTC, merged