Added Factory pattern for Populators
MarinaGotka/JavaTraining pull request #5
Opened 2021-06-10 15:32 UTC by MarinaGotka

2021-06-18 11:06 UTC, artemmoroz requested changes
May be i did not find) but i dont see any patterns here)

2021-06-18 11:06 UTC, artemmoroz commented on store/src/main/java/by/issoft/store/helpers/populators/IPopulator.java
> +    public String getName(CategoryName categoryName);
from my point, populator should have such methods as getCategories or (and) getProductsForCategory(...)

2021-06-29 16:51 UTC, MarinaGotka commented on store/src/main/java/by/issoft/store/helpers/populators/IPopulator.java
> +    public String getName(CategoryName categoryName);
Ok, I agree.

2021-07-13 15:59 UTC, artemmoroz approved these changes

2021-07-13 16:02 UTC, merged